"""Añadir columna stock_total a Herramienta

Revision ID: 461f5bbd949e
Revises: 
Create Date: 2024-11-20 00:32:15.000192

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '461f5bbd949e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('herramientas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stock_total', sa.Integer(), nullable=False))
        batch_op.alter_column(
            'estado',
            existing_type=mysql.ENUM('Disponible', 'Reservada', 'En reparación'),
            type_=sa.Enum('Disponible', 'RESERVADA', 'EN_REPARACION', name='estadoherramientaenum'),
            existing_nullable=False,
        )
        batch_op.alter_column(
            'sucursal_id',
            existing_type=mysql.INTEGER(display_width=11),
            nullable=True,
        )

    with op.batch_alter_table('reporte_arriendos', schema=None) as batch_op:
        batch_op.alter_column(
            'estado_arriendo',
            existing_type=mysql.ENUM('En proceso', 'Finalizado'),
            type_=sa.Enum('EN_PROCESO', 'FINALIZADO', name='estadoarriendoenum'),
            existing_nullable=False,
            existing_server_default=None,  # Cambiar el server_default
        )

    with op.batch_alter_table('transacciones', schema=None) as batch_op:
        batch_op.alter_column(
            'estado',
            existing_type=mysql.ENUM('Disponible', 'Reservada', 'En reparación'),
            type_=sa.Enum('Disponible', 'RESERVADA', 'EN_REPARACION', name='estadoherramientaenum'),
            existing_nullable=False,
        )

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column(
            'password_hash',
            existing_type=mysql.VARCHAR(length=255),
            type_=sa.String(length=128),
            existing_nullable=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column(
            'password_hash',
            existing_type=sa.String(length=128),
            type_=mysql.VARCHAR(length=255),
            existing_nullable=False,
        )

    with op.batch_alter_table('transacciones', schema=None) as batch_op:
        batch_op.alter_column(
            'estado',
            existing_type=sa.Enum('Disponible', 'RESERVADA', 'EN_REPARACION', name='estadoherramientaenum'),
            type_=mysql.ENUM('Disponible', 'Reservada', 'En reparación'),
            existing_nullable=False,
        )

    with op.batch_alter_table('reporte_arriendos', schema=None) as batch_op:
        batch_op.alter_column(
            'estado_arriendo',
            existing_type=sa.Enum('EN_PROCESO', 'FINALIZADO', name='estadoarriendoenum'),
            type_=mysql.ENUM('En proceso', 'Finalizado'),
            existing_nullable=False,
            existing_server_default=None,  # Cambiar el server_default
        )

    with op.batch_alter_table('herramientas', schema=None) as batch_op:
        batch_op.alter_column(
            'sucursal_id',
            existing_type=mysql.INTEGER(display_width=11),
            nullable=False,
        )
        batch_op.alter_column(
            'estado',
            existing_type=sa.Enum('Disponible', 'RESERVADA', 'EN_REPARACION', name='estadoherramientaenum'),
            type_=mysql.ENUM('Disponible', 'Reservada', 'En reparación'),
            existing_nullable=False,
        )
        batch_op.drop_column('stock_total')

    # ### end Alembic commands ###
