"""Eliminar columna tipo de la tabla transacciones y agregar estado a la tabla transacciones

Revision ID: 49d9cf16f3be
Revises: 70c914be84ba
Create Date: 2024-10-09 22:57:05.870359

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '49d9cf16f3be'
down_revision = '70c914be84ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('herramientas', schema=None) as batch_op:
        batch_op.alter_column('marca',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('codigo',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=False)

    with op.batch_alter_table('transacciones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estado', sa.Enum('DISPONIBLE', 'RESERVADA', 'EN_REPARACION', name='estadoherramientaenum'), nullable=False))
        batch_op.drop_column('tipo')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transacciones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo', mysql.VARCHAR(length=50), nullable=False))
        batch_op.drop_column('estado')

    with op.batch_alter_table('herramientas', schema=None) as batch_op:
        batch_op.alter_column('codigo',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.alter_column('marca',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=False)

    # ### end Alembic commands ###
